name: ci
permissions:
  contents: read
on:
  push: { branches: [main] }
  pull_request:
jobs:
  shell:
    uses: JakobMelchard/.github/.github/workflows/shell.yml@main
    with:
      paths: .
      severity: warning
