name: ci
permissions:
  contents: read
on:
  push: { branches: [main] }
  pull_request:
jobs:
  shell:
    uses: JakobMelchard/.github/.github/workflows/shell.yml@main
    with:
      paths: .
      severity: warning

  hooks:
    uses: JakobMelchard/.github/.github/workflows/hooks.yml@main

  bats:
    runs-on: ${{ fromJSON(vars.RUNNER_LINUX || '"ubuntu-latest"') }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with: { persist-credentials: false }
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          repository: bats-core/bats-core
          ref: eb7f42f8d608ac693d7a4b67474f6714ea68cfc5 # v1.14.0
          path: .bats
          persist-credentials: false
      - run: .bats/bin/bats test
